# Generated by Django 4.0.4 on 2022-06-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cursos', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('camada', models.IntegerField()),
                ('nacimiento', models.DateField()),
            ],
        ),
    ]
